---
- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: auditd
  vars:
    auditd_failure_mode: 1
    auditd_enable_flag: 2
    auditd_buffer_size: 32768
    auditd_reporting: true
    # https://access.redhat.com/documentation/ru-ru/red_hat_enterprise_linux/7/html/security_guide/sec-configuring_the_audit_service
    auditd_conf_lineinfile:
      - { re: '^max_log_file = .*', l: 'max_log_file = 100' }
      - { re: '^num_logs = .*',     l: 'num_logs = 30' }
      - { re: '^space_left = .*', l: 'space_left = 5%' }
      - { re: '^admin_space_left = .*', l: 'admin_space_left = 1%' }
      - { re: '^freq = .*', l: 'freq = 50' }
      - { re: '^flush = .*', l: 'flush = incremental_async' }
      # avoid 'dispatch err (pipe full) event lost' - deprecated on RHEL8
      - { re: '^disp_qos = .*', l: 'disp_qos = lossless' }
    auditd_grub_enable: true
    # Attention! those four would generate lot of logs. alternatives: sysdig/falco, systemtap, osquery...
    auditd_log_all_execve: true
    auditd_log_all_socket: false
    auditd_log_all_connect: false
    auditd_rule_rootcmd_all: false
    

